# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='pw_hash',
        ),
    ]
