# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_auto_20170202_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='biography',
            field=models.TextField(null=True),
        ),
    ]
