# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0004_auto_20170202_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Prior to adding title column', max_length=125),
        ),
    ]
