# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_post_title'),
        ('login_registration', '0004_pet_biography'),
    ]

    operations = [
    ]
