# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0005_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
