# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0006_auto_20170202_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
