# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0007_auto_20170202_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default=95008, max_length=10),
            preserve_default=False,
        ),
    ]
